# frozen_string_literal: true

task :check_coverage do
  desc 'Collates all result sets generated by the different test runners on CI/CD'
  require 'simplecov'

  SimpleCov.maximum_coverage_drop 0.5
  SimpleCov.minimum_coverage 90
  SimpleCov.collate Dir['coverage/.resultset.json']
end
