services:
  db:
    image: 'postgres:16'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gymme_backend
      POSTGRES_PASSWORD: gymme_backend
    ports:
      - '5432:5432'
  rails:
    build:
      context: .
      dockerfile: app.Dockerfile
      args:
        RAILS_ENV: production
    ports:
      - '3000:3000'
    volumes:
      - .:/GYMME-backend/app # add our local code to dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      POSTGRES_USER: gymme_backend
      POSTGRES_PASSWORD: gymme_backend
      SECRET_KEY_BASE: somerandomshit

volumes:
  postgres: