name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t gymme_backend:${{ github.sha }} .
          docker save gymme_backend:${{ github.sha }} | gzip > gymme-backend_${{ github.sha }}.tar.gz
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: gymme-backend-docker-image
          path: gymme_backend_${{ github.sha }}.tar.gz

