name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t gymme_backend:${{ github.sha }} -f app.Dockerfile .
          docker save gymme_backend:${{ github.sha }} | gzip > gymme_backend_${{ github.sha }}.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: gymme-backend-docker-image
          path: gymme_backend_${{ github.sha }}.tar.gz
    
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref_name  == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-docker-image
          path: gymme_backend_${{ github.sha }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c gymme_backend_${{ github.sha }}.tar.gz
      
      - name: Build and push Docker image
        run: |
          docker tag gymme_backend_${{ github.sha }} mirkru36/gymme:latest
          docker push mirkru36/gymme:latest

