name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t gymme_backend:${{ github.sha }} -f app.Dockerfile .
          docker save gymme_backend:${{ github.sha }} | gzip > gymme_backend_${{ github.sha }}.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: gymme-backend-docker-image
          path: gymme_backend_${{ github.sha }}.tar.gz
    
  deploy:
    name: Deploy to TBD
    runs-on: ubuntu-latest
    needs: build
    if: github.head_ref == 'main'

    steps:
      - name: Install dependencies
        run: |
          echo "TBD..."

