name: CI

on:
  push:
    branches:
      - '**'

jobs:
  setup-app:
    name: Setup Rails Application
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password

      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml

      - name: Precompile assets (if needed)
        run: |
          bin/rails assets:precompile

      - name: Save setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: gymme-backend
          path: .

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup-app
    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run tests
        run: bundle exec rspec

  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest
    needs: setup-app

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run RuboCop
        run: bundle exec rubocop

  brakeman:
    name: Run Brakeman
    runs-on: ubuntu-latest
    needs: setup-app

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run Brakeman
        run: bundle exec brakeman

  bullet:
    name: Run Bullet
    runs-on: ubuntu-latest
    needs: setup-app

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run Bullet
        run: bundle exec rails runner 'Bullet.enable = true; Bullet.start_request; Bullet.end_request; Bullet::Detector::UnusedEagerLoading.check_unused_preload_associations'
