name: CI

on:
  workflow_run:
      workflows: ["Setup Application"]
      types:
        - completed
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run tests
        run: bundle exec rspec

  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run RuboCop
        run: bundle exec rubocop

  brakeman:
    name: Run Brakeman
    runs-on: ubuntu-latest

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run Brakeman
        run: bundle exec brakeman

  bullet:
    name: Run Bullet
    runs-on: ubuntu-latest

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password
      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: gymme-backend-setup
          path: .
      - name: Run Bullet
        run: bundle exec rails runner 'Bullet.enable = true; Bullet.start_request; Bullet.end_request; Bullet::Detector::UnusedEagerLoading.check_unused_preload_associations'
