name: Deploys Image

on:
  workflow_run:
    workflows: [CI, Build Docker Image]
    types:
      - completed
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    name: Deploy to TBD
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          echo "TBD..."