name: Postgres

on:
  workflow_call:
    inputs:
      postgres-db-name:
        required: true
        type: string
      postgres-user:
        required: true
        type: string
      postgres-password:
        required: true
        type: string

jobs:
  setup-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ inputs.postgres-user }}
          POSTGRES_PASSWORD: ${{ inputs.postgres-password }}
          POSTGRES_DB: ${{ inputs.postgres-db-name }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -p 5432; do
            sleep 1
          done
