name: Setup Application

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  setup-app:
    name: Setup Rails Application
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Setup Postgres
        uses: ./.github/workflows/common/postgres.yml
        with:
          postgres-db-name: postgres
          postgres-user: postgres
          postgres-password: password

      - name: Setup Ruby
        uses: ./.github/workflows/common/ruby.yml

      - name: Precompile assets (if needed)
        run: |
          bin/rails assets:precompile

      - name: Save setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: gymme-backend
          path: .
